"""Dominant colours to colours

Revision ID: 8dfa3a337309
Revises: b690180c1801
Create Date: 2023-10-07 21:45:46.131588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8dfa3a337309'
down_revision: Union[str, None] = 'b690180c1801'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('art', sa.Column('colours', postgresql.ARRAY(sa.String()), nullable=True))
    op.drop_index('idx_dominant_color_gin', table_name='art', postgresql_using='gin')
    op.create_index('idx__color_gin', 'art', ['colours'], unique=False, postgresql_using='gin')
    op.drop_column('art', 'dominant_color')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('art', sa.Column('dominant_color', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.drop_index('idx__color_gin', table_name='art', postgresql_using='gin')
    op.create_index('idx_dominant_color_gin', 'art', ['dominant_color'], unique=False, postgresql_using='gin')
    op.drop_column('art', 'colours')
    # ### end Alembic commands ###
