"""Added created, updated columns, removed created_on columnl

Revision ID: a38a8078be31
Revises: 2739ce675fc7
Create Date: 2023-10-06 00:06:22.820210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a38a8078be31'
down_revision: Union[str, None] = '2739ce675fc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('art', sa.Column('created', sa.DateTime(), nullable=True))
    op.add_column('art', sa.Column('updated', sa.DateTime(), nullable=True))
    op.drop_index('idx_art_type_date', table_name='art')
    op.create_index('idx_art_type_date', 'art', ['type', 'created'], unique=False)
    op.drop_column('art', 'updated_on')
    op.drop_column('art', 'date_created')
    op.add_column('audio', sa.Column('created', sa.DateTime(), nullable=True))
    op.add_column('audio', sa.Column('updated', sa.DateTime(), nullable=True))
    op.drop_index('idx_audio_type_date', table_name='audio')
    op.create_index('idx_audio_type_date', 'audio', ['type', 'created'], unique=False)
    op.drop_column('audio', 'updated_on')
    op.drop_column('audio', 'date_created')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audio', sa.Column('date_created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('audio', sa.Column('updated_on', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_index('idx_audio_type_date', table_name='audio')
    op.create_index('idx_audio_type_date', 'audio', ['type', 'date_created'], unique=False)
    op.drop_column('audio', 'updated')
    op.drop_column('audio', 'created')
    op.add_column('art', sa.Column('date_created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('art', sa.Column('updated_on', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_index('idx_art_type_date', table_name='art')
    op.create_index('idx_art_type_date', 'art', ['type', 'date_created'], unique=False)
    op.drop_column('art', 'updated')
    op.drop_column('art', 'created')
    # ### end Alembic commands ###
