"""Added url fields.

Revision ID: b690180c1801
Revises: 7ec0e5ea854c
Create Date: 2023-10-06 13:29:42.131476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b690180c1801'
down_revision: Union[str, None] = '7ec0e5ea854c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('art', sa.Column('url', sa.String(), nullable=True))
    op.drop_column('art', 'image_url')
    op.add_column('audio', sa.Column('url', sa.String(), nullable=True))
    op.drop_column('audio', 'audio_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audio', sa.Column('audio_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('audio', 'url')
    op.add_column('art', sa.Column('image_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('art', 'url')
    # ### end Alembic commands ###
